language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get install xorg-dev libglu1-mesa-dev

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5 # not sure why we needed this
    packages:
      - clang-3.9

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
