language: cpp

compiler:
  - clang

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-6.0 # It's depend apt-get source
        packages:
          - clang-6.0
          - libstdc++6
    env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang-6.0"

before_install:
  - sudo apt-get install xorg-dev libglu1-mesa-dev
  - eval "${MATRIX_EVAL}"
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j8
