language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get install xorg-dev libglu1-mesa-dev

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-6.0 # It's depend apt-get source
    packages:
      - clang-6.0

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
